apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: alaska-kubectl-executor
spec:
  inputs:
    params:
    - name: path
      type: string
    resources:
    - name: repo
      type: git
    - name: cluster
      type: cluster
  steps:
  - name: kubectl-apply
    image: lachlanevenson/k8s-kubectl 
    command: ["kubectl"]
    args:
      - "--kubeconfig"
      - "/workspace/${inputs.resources.cluster.name}/kubeconfig"
      - "cluster-info"